Repository syslog-ng/syslog-ng, pull requests merged in 2018-12, with the labels that each got.

#2437 json: refine log messages to be less alarming
  modules/json/json-parser.c
Labels: in progress

#2434 mainloop-worker-io: possible refcount leak during reload/shutdown
  lib/logreader.c
  lib/logwriter.c
  lib/mainloop-io-worker.c
  lib/mainloop-io-worker.h
  modules/systemd-journal/journal-reader.c
Labels: needs-review

#2445 fix include guard in systemd-journal
  modules/systemd-journal/systemd-journal-parser.h
Labels: community-driven-merge

#2401 Remove template hex, oct number parse in configuration
  lib/cfg-lex.l
  lib/parse-number.c
  lib/parse-number.h
  lib/tests/test_parse_number.c
  modules/basicfuncs/list-funcs.c
  modules/basicfuncs/numeric-funcs.c
  modules/basicfuncs/str-funcs.c
  modules/basicfuncs/tests/test_basicfuncs.c
  modules/getent/getent-group.c
  modules/getent/getent-passwd.c
  modules/getent/getent-protocols.c
  modules/getent/getent-services.c
Labels: needs-review, user-visible-feature

#2449 Version/3.19
  NEWS.md
  README.md
  VERSION
  contrib/openbsd-packaging/syslog-ng.conf
  doc/man/dqtool.1.xml
  doc/man/loggen.1.xml
  doc/man/pdbtool.1.xml
  doc/man/syslog-ng-ctl.1.xml
  doc/man/syslog-ng-debun.1.xml
  doc/man/syslog-ng.8.xml
  doc/man/syslog-ng.conf.5.xml
  lib/tests/test_lexer.c
  lib/versioning.h
  modules/http/README.md
  modules/java-modules/common/README.md
  modules/java/README.md
  modules/java/tools/syslog-ng.conf.example
  modules/python/python-example.conf
  modules/riemann/riemann-example.conf
  modules/system-source/system-expand.sh
  packaging/debian/changelog
  packaging/debian/syslog-ng.conf
  packaging/debian/tests/config.syslog
  packaging/rhel/syslog-ng.conf
  packaging/rhel/syslog-ng.spec
  scl/graphite/README
  scl/syslog-ng.conf
  scl/syslogconf/README
  tests/functional/test_file_source.py
  tests/functional/test_filters.py
  tests/functional/test_input_drivers.py
  tests/functional/test_map_value_pairs.py
  tests/functional/test_performance.py
  tests/functional/test_python.py
  tests/functional/test_sql.py
Labels: in progress

#2465 configure: fix "--with-docbook*" option usage
  configure.ac
Labels: in progress

#2440 PytestPART1: Add some bug fixes
  tests/pytest_framework/conftest.py
  tests/pytest_framework/src/syslog_ng_config/statements/destinations/destination_driver.py
Labels: in progress

#2469 Fix app-parser() per reload memory leak
  lib/cfg-block-generator.c
  lib/cfg-block-generator.h
  lib/cfg-lexer.c
Labels: in progress

#2467 travis: refactor - use brew and apt addon instead of shell execution
  .travis.yml
  contrib/Brewfile
Labels: community-driven-merge

#2427 refactor timestamp parsing code to be less coupled with message parsing
  lib/CMakeLists.txt
  lib/Makefile.am
  lib/str-format.c
  lib/str-format.h
  lib/str-timestamp/CMakeLists.txt
  lib/str-timestamp/Makefile.am
  lib/str-timestamp/decode.c
  lib/str-timestamp/decode.h
  lib/str-timestamp/tests/CMakeLists.txt
  lib/str-timestamp/tests/Makefile.am
  lib/str-timestamp/tests/test_parse_timestamp.c
  lib/template/macros.c
  lib/timeutils.c
  lib/timeutils.h
  modules/snmptrapd-parser/snmptrapd-header-parser.c
  modules/syslogformat/syslog-format.c
  tests/copyright/policy
Labels: needs-review
