Repository syslog-ng/syslog-ng, pull requests merged in 2018-06, with the labels that each got.

#2081 cfg: free PersistState after deallocating all LogPipe objects
  lib/cfg.c
Labels: needs-review

#2079 Use multitransport when proto needs it
  lib/logproto/logproto-client.h
  lib/logproto/logproto-server.h
  modules/afsocket/afsocket-dest.c
  modules/afsocket/afsocket-source.c
  modules/afsocket/transport-mapper-inet.c
  modules/afsocket/transport-mapper.h
Labels: in progress

#2083 Fix test_rcptid
  lib/tests/test_rcptid.c
Labels: in progress

#2086 memleak fixes: appmodel and varargs
  lib/cfg-block.c
  modules/appmodel/appmodel-grammar.ym
Labels: in progress

#2082 multitransport: keep I/O condition synced
  lib/transport/multitransport.c
  lib/transport/transport-factory-tls.c
  lib/transport/transport-factory-tls.h
Labels: in progress

#2091 Transport factory make type public
  lib/transport/transport-factory-socket.c
  lib/transport/transport-factory-socket.h
  lib/transport/transport-factory-tls.c
  lib/transport/transport-factory-tls.h
Labels: in progress

#2085 telegram destination + urlencode template function
  modules/basicfuncs/Makefile.am
  modules/basicfuncs/basic-funcs.c
  modules/basicfuncs/tests/test_basicfuncs.c
  modules/basicfuncs/urlencode.c
  packaging/debian/syslog-ng-mod-http.install
  scl/CMakeLists.txt
  scl/Makefile.am
  scl/telegram/telegram.conf
Labels: in progress

#2062 Lexer test coverage improvements
  Makefile.am
  cmake/add_tests.cmake
  lib/filter/tests/CMakeLists.txt
  lib/filter/tests/Makefile.am
  lib/tests/Makefile.am
  lib/tests/test_lexer.c
  lib/tests/testdata-lexer/include-test/bar.conf
  lib/tests/testdata-lexer/include-test/baz.conf
  lib/tests/testdata-lexer/include-test/foo.conf
  lib/tests/testdata-lexer/include-test/invalid~include~file.conf
  modules/geoip2/tests/CMakeLists.txt
  modules/geoip2/tests/Makefile.am
Labels: in progress

#2067 nvtable: deserialize sdata invalid if fixed up
  lib/logmsg/logmsg-serialize-fixup.c
  lib/logmsg/tests/CMakeLists.txt
  lib/logmsg/tests/test_logmsg_serialize.c
Labels: in progress

#2101 Always add test datafiles to the dist tarball
  lib/Makefile.am
  lib/tests/Makefile.am
Labels: needs-review

#2111 secret-storage: rename PAGESIZE variables to pagesize
  lib/secret-storage/nondumpable-allocator.c
  lib/secret-storage/tests/test_nondumpable_allocator.c
  lib/secret-storage/tests/test_secret_storage.c
Labels: community-driven-merge

#1612 bugfix (fixes #1570): use sd_journald_test_cursor() from systemd-jour…
  modules/systemd-journal/journal-reader.c
  modules/systemd-journal/journald-subsystem.c
  modules/systemd-journal/journald-subsystem.h
  modules/systemd-journal/tests/journald-mock.c
Labels: bug, in progress, needs-review

#2118 Rewrite patternDB test cases based on criterion
  modules/dbparser/tests/CMakeLists.txt
  modules/dbparser/tests/Makefile.am
  modules/dbparser/tests/test_parsers.c
  modules/dbparser/tests/test_parsers_e2e.c
  modules/dbparser/tests/test_patterndb.c
  modules/dbparser/tests/test_patterndb.h
Labels: needs-review

#2100 build: Link everything to libsecret-storage
  configure.ac
  lib/logproto/tests/Makefile.am
  syslog-ng/Makefile.am
Labels: in progress

#2088 cfg-block: mandatory parameters
  lib/cfg-args.c
  lib/cfg-args.h
  lib/cfg-block.c
  lib/cfg-lex.l
  lib/tests/CMakeLists.txt
  lib/tests/Makefile.am
  lib/tests/test_cfg_lexer_subst.c
  lib/tests/test_lexer_block.c
  scl/default-network-drivers/plugin.conf
  scl/snmptrap/snmptrapd-source.conf
Labels: needs-review
