Repository syslog-ng/syslog-ng, pull requests merged in 2018-10, with the labels that each got.

#2326 Update deprecated use of tcp()/udp() to network(). This addresses #2322
  scl/loggly/loggly.conf
  scl/logmatic/logmatic.conf
  scl/syslogconf/convert-syslogconf.awk
Labels: community-driven-merge

#2343 amqp configurable max connection and frame size
  modules/afamqp/CMakeLists.txt
  modules/afamqp/Makefile.am
  modules/afamqp/afamqp-grammar.ym
  modules/afamqp/afamqp-parser.c
  modules/afamqp/afamqp-plugin.c
  modules/afamqp/afamqp.c
  modules/afamqp/afamqp.h
Labels: user-visible-feature

#2308 Python source
  lib/cfg-grammar.y
  lib/logreader.h
  lib/logthrsource/logthrsourcedrv.c
  lib/logthrsource/logthrsourcedrv.h
  modules/examples/sources/threaded-diskq-source/threaded-diskq-source-grammar.ym
  modules/examples/sources/threaded-random-generator/threaded-random-generator-grammar.ym
  modules/python/CMakeLists.txt
  modules/python/Makefile.am
  modules/python/compat/compat-python-v2.c
  modules/python/compat/compat-python-v3.c
  modules/python/compat/compat-python.c
  modules/python/compat/compat-python.h
  modules/python/python-debugger.c
  modules/python/python-dest.c
  modules/python/python-fetcher.c
  modules/python/python-fetcher.h
  modules/python/python-grammar.ym
  modules/python/python-helpers.c
  modules/python/python-helpers.h
  modules/python/python-logmsg.c
  modules/python/python-parser.c
  modules/python/python-plugin.c
  modules/python/python-source.c
  modules/python/python-source.h
  modules/python/tests/CMakeLists.txt
  modules/python/tests/Makefile.am
  modules/python/tests/test_python_logmsg.c
Labels: needs-review

#2345 Issue 2304 | verify the configuration is the same as on the disk
  lib/control/control-commands.c
  lib/mainloop.c
  lib/mainloop.h
  syslog-ng-ctl/syslog-ng-ctl.c
Labels: community-driven-merge, user-visible-feature

#2363 Afsocket remove unused functions/bitfields
  modules/afsocket/afinet-dest.c
  modules/afsocket/afsocket-dest.h
  modules/afsocket/afsocket-source.h
  modules/afsocket/afunix-source.c
  modules/afsocket/systemd-syslog-source.c
Labels: community-driven-merge

#2379 Udp reuseport
  configure.ac
  modules/afsocket/afsocket-grammar.ym
  modules/afsocket/afsocket-parser.c
  modules/afsocket/socket-options.c
  modules/afsocket/socket-options.h
Labels: user-visible-feature

#2097 Afsql threaded dest driver
  modules/afsql/afsql-grammar.ym
  modules/afsql/afsql-parser.c
  modules/afsql/afsql.c
  modules/afsql/afsql.h
Labels: in progress
