Repository syslog-ng/syslog-ng, pull requests merged in 2018-09, with the labels that each got.

#2190 Http framing support for batches
  modules/http/http-grammar.ym
  modules/http/http-parser.c
  modules/http/http.c
  modules/http/http.h
Labels: in progress

#2243 Processed timestamp
  lib/logmsg/logmsg-serialize.c
  lib/logmsg/logmsg-serialize.h
  lib/logmsg/logmsg.c
  lib/logmsg/logmsg.h
  lib/logmsg/serialization.h
  lib/logmsg/tests/test_logmsg_serialize.c
  lib/logmsg/tests/test_timestamp_serialize.c
  lib/logmsg/timestamp-serialize.c
  lib/logstamp.h
  lib/template/macros.c
  lib/template/macros.h
  lib/value-pairs/tests/test_value_pairs.c
Labels: planned

#2252 Rewrite dbparser tests based on criterion
  modules/dbparser/tests/CMakeLists.txt
  modules/dbparser/tests/test_patternize.c
  modules/dbparser/tests/test_radix.c
  modules/dbparser/tests/test_timer_wheel.c
Labels: needs-review

#2251 implement flush-timeout() for http
  .travis.yml
  lib/logthrdestdrv.c
  lib/logthrdestdrv.h
  lib/tests/test_logthrdestdrv.c
  modules/http/http-grammar.ym
  modules/http/http.c
  modules/http/http.h
Labels: user-visible-feature

#2247 Threaded source and fetcher
  lib/CMakeLists.txt
  lib/Makefile.am
  lib/logthrsource/CMakeLists.txt
  lib/logthrsource/Makefile.am
  lib/logthrsource/logthrfetcherdrv.c
  lib/logthrsource/logthrfetcherdrv.h
  lib/logthrsource/logthrsourcedrv.c
  lib/logthrsource/logthrsourcedrv.h
  lib/logthrsource/tests/CMakeLists.txt
  lib/logthrsource/tests/Makefile.am
  lib/logthrsource/tests/test_logthrfetcherdrv.c
  lib/logthrsource/tests/test_logthrsourcedrv.c
  tests/copyright/policy
Labels: in progress

#2257 Hdfs time-reap
  modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsDestination.java
  modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsFile.java
  modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsOptions.java
  modules/java/native/java-destination.c
  scl/hdfs/plugin.conf
Labels: user-visible-feature

#2281 Update data type to avoid conversion.
  lib/stats/stats-counter.h
Labels: community-driven-merge

#2280 syslog-ng-ctl config to print pre-processed configuration
  lib/cfg.c
  lib/cfg.h
  lib/control/control-commands.c
  syslog-ng-ctl/syslog-ng-ctl.c
Labels: user-visible-feature

#2278 basicfuncs: url-decode template function
  modules/basicfuncs/basic-funcs.c
  modules/basicfuncs/tests/test_basicfuncs.c
  modules/basicfuncs/urlencode.c
Labels: community-driven-merge, user-visible-feature

#2248 "Examples" module
  CMakeLists.txt
  configure.ac
  modules/CMakeLists.txt
  modules/Makefile.am
  modules/diskq/CMakeLists.txt
  modules/examples/CMakeLists.txt
  modules/examples/Makefile.am
  modules/examples/example-plugins.c
  modules/examples/sources/msg-generator/CMakeLists.txt
  modules/examples/sources/msg-generator/Makefile.am
  modules/examples/sources/msg-generator/README.md
  modules/examples/sources/msg-generator/msg-generator-grammar.ym
  modules/examples/sources/msg-generator/msg-generator-parser.c
  modules/examples/sources/msg-generator/msg-generator-parser.h
  modules/examples/sources/msg-generator/msg-generator-source-options.h
  modules/examples/sources/msg-generator/msg-generator-source.c
  modules/examples/sources/msg-generator/msg-generator-source.h
  modules/examples/sources/msg-generator/msg-generator.c
  modules/examples/sources/msg-generator/msg-generator.h
  modules/examples/sources/threaded-diskq-source/CMakeLists.txt
  modules/examples/sources/threaded-diskq-source/Makefile.am
  modules/examples/sources/threaded-diskq-source/README.md
  modules/examples/sources/threaded-diskq-source/threaded-diskq-source-grammar.ym
  modules/examples/sources/threaded-diskq-source/threaded-diskq-source-parser.c
  modules/examples/sources/threaded-diskq-source/threaded-diskq-source-parser.h
  modules/examples/sources/threaded-diskq-source/threaded-diskq-source.c
  modules/examples/sources/threaded-diskq-source/threaded-diskq-source.h
  modules/examples/sources/threaded-random-generator/CMakeLists.txt
  modules/examples/sources/threaded-random-generator/Makefile.am
  modules/examples/sources/threaded-random-generator/README.md
  modules/examples/sources/threaded-random-generator/threaded-random-generator-grammar.ym
  modules/examples/sources/threaded-random-generator/threaded-random-generator-parser.c
  modules/examples/sources/threaded-random-generator/threaded-random-generator-parser.h
  modules/examples/sources/threaded-random-generator/threaded-random-generator.c
  modules/examples/sources/threaded-random-generator/threaded-random-generator.h
  packaging/debian/Makefile.am
  packaging/debian/control
  packaging/debian/syslog-ng-mod-examples.install
  syslog-ng-config.h.in
  tests/copyright/policy
Labels: needs-review

#2289 templates: get rid off the args_lock
  lib/template/compiler.c
  lib/template/function.h
  lib/template/simple-function.c
  lib/template/simple-function.h
  lib/template/templates.c
  lib/template/templates.h
  lib/template/tests/test_template.c
  modules/basicfuncs/basic-funcs.c
  modules/basicfuncs/cond-funcs.c
  modules/basicfuncs/context-funcs.c
  modules/basicfuncs/numeric-funcs.c
  modules/basicfuncs/str-funcs.c
  modules/cryptofuncs/cryptofuncs.c
  modules/geoip/tfgeoip.c
  modules/geoip2/tfgeoip.c
  modules/stardate/stardate.c
Labels: user-visible-feature

#2290 app-parser: set ${.app.name} to the application identified
  modules/appmodel/app-parser-generator.c
Labels: user-visible-feature

#2287 Value pairs improvements
  lib/cfg-grammar.y
  lib/value-pairs/cmdline.c
  lib/value-pairs/tests/test_value_pairs.c
  lib/value-pairs/transforms.c
  lib/value-pairs/transforms.h
  lib/value-pairs/value-pairs.c
  modules/json/tests/test_format_json.c
Labels: user-visible-feature

#2299 telegram, urlencode: api changes
  modules/basicfuncs/basic-funcs.c
  modules/basicfuncs/tests/test_basicfuncs.c
  scl/telegram/telegram.conf
Labels: user-visible-feature

#2286 json: fix the literal() type hint
  modules/json/format-json.c
  modules/json/tests/test_format_json.c
Labels: user-visible-feature

#2310 examples: fix conditional include (Makefile)
  modules/examples/Makefile.am
  modules/examples/sources/threaded-random-generator/Makefile.am
Labels: needs-review

#2305 warning elimination: pointer arithmetics
  CMakeLists.txt
  Makefile.am
  configure.ac
  lib/logmsg/nvtable-serialize-legacy.c
  lib/persist-state.c
  lib/ringbuffer.c
  lib/secret-storage/nondumpable-allocator.c
  modules/affile/logproto-file-writer.c
  modules/dbparser/Makefile.am
  modules/dbparser/pdb-program.c
  modules/dbparser/pdb-ruleset.c
  modules/dbparser/pdbtool/Makefile.am
  modules/dbparser/pdbtool/pdbtool.c
  modules/dbparser/radix.c
  modules/dbparser/radix.h
  modules/dbparser/tests/Makefile.am
  modules/dbparser/tests/test_parsers.c
  modules/dbparser/tests/test_radix.c
  modules/diskq/tests/Makefile.am
Labels: community-driven-merge
