Repository syslog-ng/syslog-ng, pull requests merged in 2018-04, with the labels that each got.

#1957 Fix stomp template option
  modules/afstomp/afstomp.c
  modules/afstomp/tests/CMakeLists.txt
  modules/afstomp/tests/test_stomp_proto.c
Labels: in progress

#1930 Extend LogProto
  lib/cfg-grammar.y
  lib/gsockaddr.c
  lib/gsockaddr.h
  lib/logproto/logproto-client.h
  lib/logproto/logproto-server.h
  lib/logreader.c
  lib/logwriter.c
  lib/transport/transport-socket.c
  lib/transport/transport-tls.c
  modules/afsocket/afsocket-dest.c
  modules/afsocket/afsocket-grammar.ym
  modules/afsocket/afsocket-source.c
Labels: needs-review

#1968 testing: fixing symbol redefinition error
  libtest/cr_template.c
  libtest/cr_template.h
Labels: needs-review

#1966 declaration related warnings fixes
  .travis.yml
  Makefile.am
  configure.ac
  lib/cfg.c
  lib/gprocess.c
  lib/mainloop.c
  lib/scanner/kv-scanner/kv-scanner.c
  lib/secret-storage/tests/test_secret_storage.c
  lib/service-management.c
  lib/value-pairs/tests/test_value_pairs.c
  modules/add-contextual-data/add-contextual-data-filter-selector.c
  syslog-ng-ctl/syslog-ng-ctl.c
Labels: community-driven-merge

#1958 python: fix the syntax for options() in python destination to make it in parity with python parser
  modules/python/python-grammar.ym
Labels: community-driven-merge, needs-review

#1967 nvtable: deserialized handle access crash
  lib/logmsg/logmsg-serialize-fixup.c
Labels: needs-review

#1970 Fix possible LogMessage-related crash (NVTable)
  lib/logmsg/nvtable.h
Labels: needs-review

#1950 Dbld refinements2
  dbld/images/devshell-apt/all.txt
  dbld/images/devshell-apt/artful.txt
  dbld/images/devshell-pip/all.txt
  dbld/images/devshell.dockerfile
  dbld/images/helpers/functions.sh
  dbld/images/required-apt/all.txt
  dbld/make
  dbld/rules
  dbld/shell
Labels: needs-review

#1975 log_writer_write_message: same modification as PR 1890
  lib/logwriter.c
Labels: needs-review

#1976 Fix possible crash in afsocket
  modules/afsocket/afsocket-source.c
Labels: in progress

#1973 Switch case default warning fixes
  Makefile.am
  lib/block-ref-grammar.ym
  lib/cfg-grammar.y
  lib/cfg-lexer-subst.c
  lib/cfg-parser.c
  lib/logproto/logproto-multiline-server.c
  lib/pragma-grammar.ym
  lib/str-repr/decode.c
  lib/template/macros.c
  lib/template/repr.c
  lib/template/templates.c
  modules/afamqp/afamqp.c
  modules/afprog/afprog.c
  modules/afsocket/afsocket-dest.c
  modules/afsocket/afsocket-source.c
  modules/afsocket/socket-options-inet.c
  modules/afuser/afuser-grammar.ym
  modules/diskq/diskq-grammar.ym
Labels: community-driven-merge, in progress

#1977 Partially revert some time-reap changes, to lessen the impact of a race
  modules/affile/affile-dest.c
Labels: needs-review, planned

#1971 Enable warning: warning manipulation
  Makefile.am
  configure.ac
Labels: needs-review

#1984 dbld/images/devshell: generate utf8 locale
  dbld/images/devshell-apt/all.txt
  dbld/images/devshell.dockerfile
Labels: in progress

#1942 Fix macOS build (automake + CMake)
  .travis.yml
  CMakeLists.txt
  cmake/add_tests.cmake
  configure.ac
  contrib/Brewfile
  contrib/Makefile.am
  lib/secret-storage/CMakeLists.txt
  lib/secret-storage/Makefile.am
  modules/add-contextual-data/tests/Makefile.am
  modules/afamqp/CMakeLists.txt
  modules/affile/CMakeLists.txt
  modules/affile/tests/test_directory_monitor.c
  modules/python/tests/test_python_logmsg.c
  modules/redis/CMakeLists.txt
  syslog-ng-config.h.in
Labels: needs-review, planned

#1989 test_run_id: rewrite test in criterion
  lib/tests/CMakeLists.txt
  lib/tests/test_runid.c
Labels: community-driven-merge

#1947 Fix default network drivers
  lib/cfg-lexer.c
  lib/cfg-lexer.h
  lib/tlscontext.c
  lib/tlscontext.h
  lib/transport/transport-tls.c
  modules/afsocket/afsocket-grammar.ym
  modules/afsocket/tests/test-transport-mapper-inet.c
  scl/default-network-drivers/plugin.conf
  scl/syslog-ng.conf
Labels: needs-review

#1905 afsocket: port basic client side failover functionality
  lib/logwriter.c
  modules/afsocket/afinet-dest.c
  modules/afsocket/afinet-dest.h
  modules/afsocket/afsocket-dest.c
  modules/afsocket/afsocket-grammar.ym
  modules/afsocket/afsocket-parser.c
Labels: needs-review

#1948 log_msg_append_format_sdata: added block name sanitization.
  lib/logmsg/logmsg.c
  lib/logmsg/tests/test_log_message.c
Labels: needs-review

#1979 default-network-drivers: Use if-else statements
  scl/default-network-drivers/plugin.conf
Labels: in progress

#1994 Upgrage macOS version in Travis
  .travis.yml
  configure.ac
  lib/plugin.c
Labels: in progress

#1956 pragma module-dependency for optional include
  lib/pragma-grammar.ym
  lib/pragma-parser.c
  scl/cim/template.conf
  scl/elasticsearch/plugin.conf
  scl/ewmm/ewmm.conf
  scl/graylog2/plugin.conf
  scl/loggly/loggly.conf
  scl/logmatic/logmatic.conf
Labels: needs-review

#1998 hook-commands: does not compile with cmake
  modules/CMakeLists.txt
  modules/hook-commands/CMakeLists.txt
Labels: in progress

#1997 Fix OpenSSL 1.1 support
  cmake/openssl_functions.cmake
  configure.ac
  lib/compat/openssl_support.c
  lib/compat/openssl_support.h
  lib/tlscontext.c
  syslog-ng-config.h.in
Labels: needs-review

#2000 tlscontext: set the ssl session id context to a static value
  lib/tlscontext.c
Labels: in progress

#2001 Preparations for 3.15.1
  NEWS.md
  README.md
  VERSION
  contrib/openbsd-packaging/syslog-ng.conf
  doc/man/dqtool.1.xml
  doc/man/loggen.1.xml
  doc/man/pdbtool.1.xml
  doc/man/syslog-ng-ctl.1.xml
  doc/man/syslog-ng-debun.1.xml
  doc/man/syslog-ng.8.xml
  doc/man/syslog-ng.conf.5.xml
  lib/versioning.h
  modules/http/README.md
  modules/java-modules/common/README.md
  modules/java/README.md
  modules/java/tools/syslog-ng.conf.example
  modules/python/python-example.conf
  modules/riemann/riemann-example.conf
  modules/system-source/system-expand.sh
  packaging/debian/changelog
  packaging/debian/syslog-ng.conf
  packaging/debian/tests/config.syslog
  packaging/rhel/syslog-ng.conf
  scl/graphite/README
  scl/syslog-ng.conf
  scl/syslogconf/README
  tests/functional/test_file_source.py
  tests/functional/test_filters.py
  tests/functional/test_input_drivers.py
  tests/functional/test_map_value_pairs.py
  tests/functional/test_performance.py
  tests/functional/test_python.py
  tests/functional/test_sql.py
Labels: in progress
