Repository syslog-ng/syslog-ng, pull requests merged in 2018-03, with the labels that each got.

#1902 cmake: fixing different naming of getent between autotools and cmake
  modules/getent/CMakeLists.txt
Labels: needs-review

#1904 Fix compile issue #1901 on freebsd
  syslog-ng-ctl/syslog-ng-ctl.c
Labels: in progress

#1906 packaging: remove separate scl.conf
  packaging/debian/Makefile.am
  packaging/debian/scl.conf
  packaging/debian/syslog-ng-core.install
Labels: in progress

#1910 JessieDocker: Update automake in Jessie dev-dependencies
  dbld/images/jessie/dev-dependencies.txt
Labels: in progress

#1907 python: make init() optional for destinations
  modules/python/python-dest.c
Labels: community-driven-merge, in progress

#1903 Bug 1896 fixed
  modules/python/sngexample.py
Labels: community-driven-merge, in progress

#1908 [WIP]Readme: Minor updates in README.md file
  README.md
Labels: in progress

#1915 eventlog: avoid linking to old system libevtlog libraries
  .travis.yml
  configure.ac
Labels: needs-review

#1917 Fix TLS-based destinations in case of a missing client key/cert
  lib/tlscontext.c
  modules/afsocket/transport-mapper-inet.c
Labels: needs-review

#1918 Dbld: Update package list for Debian Jessie
  dbld/generate-debian-directory
  dbld/images/required-apt/all.txt
  dbld/images/required-apt/artful.txt
  dbld/images/required-apt/trusty.txt
  dbld/images/required-apt/xenial.txt
  dbld/images/required-obs/jessie.txt
Labels: in progress

#1897 Added g_list_free_full in lib/compat/glib & configure.ac
  configure.ac
  lib/compat/glib.c
  lib/compat/glib.h
  lib/secret-storage/secret-storage.c
Labels: community-driven-merge, in progress

#1856 add conditionals into the config syntax
  lib/cfg-grammar.y
  lib/cfg-parser.c
  lib/cfg-tree.c
  lib/cfg-tree.h
  lib/logpipe.h
  scl/cisco/plugin.conf
  scl/solaris/plugin.conf
Labels: needs-review

#1914 Make the data type explicit in transport mock
  libtest/mock-transport.c
  libtest/mock-transport.h
Labels: community-driven-merge, needs-review

#1899 logmatcher: remove POSIX regexp support
  lib/filter/tests/test_filters.c
  lib/logmatcher.c
  lib/logmatcher.h
  tests/unit/test_matcher.c
Labels: needs-review

#1928 template: remove unneeded name argument from call sites
  modules/graphite/graphite-output.c
  modules/java/native/java-destination.c
Labels: needs-review

#1927 Dbld login and image targets
  dbld/rules
Labels: in progress

#1938 pkg-config files correction
  Makefile.am
  configure.ac
  modules/add-contextual-data/Makefile.am
  packaging/rhel/syslog-ng.spec
  syslog-ng-add-contextual-data.pc.cmake
  syslog-ng-add-contextual-data.pc.in
  syslog-ng.pc.cmake
  syslog-ng.pc.in
Labels: in progress

#1935 file source filename corruption in case of missing path
  lib/file-perms.c
  lib/file-perms.h
  modules/affile/file-opener.c
  modules/affile/file-opener.h
Labels: needs-review

#1924 Diskq: Fix crash when corrupt disk-queue is read (during move)
  lib/logmsg/logmsg.c
  modules/diskq/logqueue-disk-non-reliable.c
Labels: needs-review

#1937 Dbld refinements
  .travis.yml
  dbld/bootstrap
  dbld/deb
  dbld/images/centos6.dockerfile
  dbld/images/centos7.dockerfile
  dbld/images/required-apt/all.txt
  dbld/images/required-yum/all.txt
  dbld/rules
  dbld/shell
  dbld/tarball
  requirements.txt
Labels: in progress

#1944 afamqp: LogTemplateOptions fix
  modules/afamqp/afamqp.c
Labels: community-driven-merge, needs-review

#1889 wildcard file source: fixing various crashes
  lib/logpipe.h
  lib/persist-state.c
  modules/affile/directory-monitor-inotify.c
  modules/affile/file-reader.c
  modules/affile/file-reader.h
  modules/affile/poll-file-changes.c
  modules/affile/wildcard-source.c
Labels: needs-review

#1946 Fix scratch-buffer memory usage in threaded destinations
  lib/logthrdestdrv.c
  lib/mainloop-io-worker.c
Labels: needs-review

#1790 Rewrite/add template-related unit tests
  CMakeLists.txt
  Makefile.am
  lib/Makefile.am
  lib/template/tests/CMakeLists.txt
  lib/template/tests/Makefile.am
  lib/template/tests/test_template.c
  lib/template/tests/test_template_speed.c
  libtest/CMakeLists.txt
  libtest/Makefile.am
  libtest/cr_template.c
  libtest/cr_template.h
  modules/basicfuncs/tests/CMakeLists.txt
  modules/basicfuncs/tests/test_basicfuncs.c
  modules/cef/tests/CMakeLists.txt
  modules/cef/tests/test-format-cef-extension.c
  modules/cryptofuncs/tests/CMakeLists.txt
  modules/cryptofuncs/tests/test_cryptofuncs.c
  modules/graphite/CMakeLists.txt
  modules/graphite/Makefile.am
  modules/graphite/tests/CMakeLists.txt
  modules/graphite/tests/Makefile.am
  modules/graphite/tests/test_graphite_output.c
  modules/json/tests/CMakeLists.txt
  modules/json/tests/test_format_json.c
  modules/kvformat/tests/CMakeLists.txt
  modules/kvformat/tests/test_format_welf.c
  modules/stardate/tests/CMakeLists.txt
  modules/stardate/tests/test_stardate.c
  modules/tagsparser/tests/test_tagsparser.c
Labels: needs-review

#1926 basicfuncs: add support for negative indexes in $(list-nth)
  modules/basicfuncs/list-funcs.c
  modules/basicfuncs/tests/test_basicfuncs.c
Labels: in progress

#1932 Improve error reporting
  lib/cfg-block-generator.c
  lib/cfg-block-generator.h
  lib/cfg-block.c
  lib/cfg-block.h
  lib/cfg-grammar.y
  lib/cfg-lexer.c
  lib/cfg-lexer.h
  lib/cfg-parser.c
Labels: in progress

#1954 libsyslog-ng: missing dependency libsecret-storage
  lib/Makefile.am
Labels: in progress
