Repository syslog-ng/syslog-ng, pull requests merged in 2018-05, with the labels that each got.

#2008 mainloop-worker: fix thread_id allocation for more than 32 CPUs
  lib/mainloop-worker.c
Labels: in progress

#2007 CMake modernization pt. 1
  CMakeLists.txt
  cmake/add_tests.cmake
  dev-utils/plugin_skeleton_creator/plugin_template_CMakeLists.txt
  lib/CMakeLists.txt
  lib/eventlog/CMakeLists.txt
  lib/filter/tests/CMakeLists.txt
  lib/logmsg/logmsg.c
  lib/secret-storage/CMakeLists.txt
  lib/secret-storage/nondumpable-allocator.h
  lib/secret-storage/secret-storage.h
  lib/secret-storage/tests/test_nondumpable_allocator.c
  lib/secret-storage/tests/test_secret_storage.c
  lib/value-pairs/tests/CMakeLists.txt
  libtest/CMakeLists.txt
  modules/add-contextual-data/CMakeLists.txt
  modules/afamqp/CMakeLists.txt
  modules/affile/CMakeLists.txt
  modules/affile/tests/CMakeLists.txt
  modules/affile/tests/Makefile.am
  modules/affile/tests/test_file_opener.c
  modules/afprog/CMakeLists.txt
  modules/afsocket/CMakeLists.txt
  modules/afuser/CMakeLists.txt
  modules/cef/CMakeLists.txt
  modules/csvparser/CMakeLists.txt
  modules/date/CMakeLists.txt
  modules/dbparser/CMakeLists.txt
  modules/dbparser/pdbtool/CMakeLists.txt
  modules/dbparser/tests/CMakeLists.txt
  modules/diskq/CMakeLists.txt
  modules/diskq/tests/CMakeLists.txt
  modules/geoip2/tests/CMakeLists.txt
  modules/hook-commands/CMakeLists.txt
  modules/java/native/java-class-loader.c
  modules/java/native/java_machine.c
  modules/kvformat/CMakeLists.txt
  modules/native/CMakeLists.txt
  modules/openbsd/CMakeLists.txt
  modules/pseudofile/CMakeLists.txt
  modules/python/python-tf.h
  modules/redis/CMakeLists.txt
  modules/snmptrapd-parser/CMakeLists.txt
  modules/syslogformat/CMakeLists.txt
  modules/systemd-journal/CMakeLists.txt
  modules/systemd-journal/tests/CMakeLists.txt
  modules/tagsparser/CMakeLists.txt
  modules/xml/CMakeLists.txt
  tests/functional/CMakeLists.txt
  tests/loggen/CMakeLists.txt
Labels: needs-review

#1999 errno safe evtlog
  lib/cfg-lexer.c
  lib/cfg.c
  lib/control/control-server-unix.c
  lib/control/control-server.c
  lib/dnscache.c
  lib/filter/filter-in-list.c
  lib/gprocess.c
  lib/logproto/logproto-buffered-server.c
  lib/logproto/logproto-framed-server.c
  lib/logproto/logproto-text-client.c
  lib/messages.h
  lib/persist-state.c
  lib/plugin.c
  lib/tests/CMakeLists.txt
  lib/tests/Makefile.am
  lib/tests/test_messages.c
  lib/tlscontext.c
  modules/affile/affile-dest.c
  modules/affile/directory-monitor-inotify.c
  modules/affile/directory-monitor.c
  modules/affile/file-reader.c
  modules/affile/logproto-file-writer.c
  modules/affile/poll-file-changes.c
  modules/afprog/afprog.c
  modules/afsocket/afsocket-dest.c
  modules/afsocket/afsocket-source.c
  modules/afsocket/transport-mapper.c
  modules/afsql/afsql.c
  modules/afstomp/stomp.c
  modules/afstreams/afstreams.c
  modules/confgen/confgen-plugin.c
  modules/dbparser/pdb-load.c
  modules/diskq/qdisk.c
  modules/getent/getent-group.c
  modules/getent/getent-passwd.c
  modules/openbsd/openbsd-driver.c
  modules/pseudofile/pseudofile.c
  modules/riemann/riemann.c
  modules/system-source/system-source.c
Labels: needs-review

#2015 eventlog: Extend evtlog.h to use evt_tag_inaddr/inaddr6 functions on …
  lib/eventlog/src/evtlog.h
Labels: community-driven-merge

#2013 Add per-source counters to "src.host" and "src.sender"
  lib/logsource.c
Labels: needs-review

#2006 Modify the loggen.c license from GPL to LGPL [skip-ci]
  tests/copyright/policy
  tests/loggen/loggen.c
Labels: needs-review

#1996 floating point warning fixes
  Makefile.am
  lib/logwriter.c
  lib/tests/CMakeLists.txt
  lib/tests/test_lexer.c
  lib/timeutils.c
  lib/type-hinting.c
  libtest/testutils.c
  modules/dbparser/groupingby.c
  modules/dbparser/patterndb.c
  modules/dbparser/patternize.c
  modules/geoip/geoip-parser.c
  modules/geoip2/maxminddb-helper.c
  modules/pacctformat/pacct-format.c
  modules/riemann/riemann.c
  tests/loggen/loggen.c
Labels: community-driven-merge, in progress

#1987 Loggen refactor
  CMakeLists.txt
  Makefile.am
  configure.ac
  tests/loggen/CMakeLists.txt
  tests/loggen/Makefile.am
  tests/loggen/file_reader.c
  tests/loggen/file_reader.h
  tests/loggen/loggen.c
  tests/loggen/loggen.md
  tests/loggen/loggen_helper.c
  tests/loggen/loggen_helper.h
  tests/loggen/loggen_plugin.c
  tests/loggen/loggen_plugin.h
  tests/loggen/logline_generator.c
  tests/loggen/logline_generator.h
  tests/loggen/socket_plugin/CMakeLists.txt
  tests/loggen/socket_plugin/Makefile.am
  tests/loggen/socket_plugin/socket_plugin.c
  tests/loggen/ssl_plugin/CMakeLists.txt
  tests/loggen/ssl_plugin/Makefile.am
  tests/loggen/ssl_plugin/ssl_plugin.c
Labels: needs-review

#1980 rpm generation process update
  dbld/images/helpers/functions.sh
  dbld/images/required-epel/all.txt
  dbld/rpm
  packaging/rhel/syslog-ng.spec
Labels: needs-review

#2021 Fix deb package build issue caused by new loggen
  packaging/debian/syslog-ng-core.install
Labels: in progress

#1974 F/delete wildcard file
  CMakeLists.txt
  configure.ac
  lib/logpipe.h
  lib/logreader.c
  lib/logsource.c
  lib/logsource.h
  modules/affile/CMakeLists.txt
  modules/affile/Makefile.am
  modules/affile/collection-comparator.c
  modules/affile/collection-comparator.h
  modules/affile/directory-monitor-inotify.c
  modules/affile/directory-monitor-poll.c
  modules/affile/directory-monitor.c
  modules/affile/directory-monitor.h
  modules/affile/file-list.c
  modules/affile/file-list.h
  modules/affile/file-reader.c
  modules/affile/file-reader.h
  modules/affile/poll-file-changes.c
  modules/affile/tests/CMakeLists.txt
  modules/affile/tests/Makefile.am
  modules/affile/tests/test_collection_comparator.c
  modules/affile/tests/test_file_list.c
  modules/affile/tests/test_wildcard_file_reader.c
  modules/affile/wildcard-file-reader.c
  modules/affile/wildcard-file-reader.h
  modules/affile/wildcard-source.c
  modules/affile/wildcard-source.h
  syslog-ng-config.h.in
Labels: in progress

#2023 Loggen refactor fixes
  tests/loggen/loggen_helper.c
  tests/loggen/logline_generator.c
Labels: needs-review

#2026 Rewrite some unit tests based on criterion
  lib/tests/test_hostname.c
  lib/tests/test_pathutils.c
  lib/tests/test_str-utils.c
Labels: needs-review

#2022 configure.ac: Fix mixed linking
  configure.ac
  modules/diskq/Makefile.am
  syslog-ng-ctl/Makefile.am
Labels: compile related, in progress

#2043 syslog-ng-ctl: fix shifting of the raw_query_params
  syslog-ng-ctl/syslog-ng-ctl.c
Labels: needs-review

#2039 Rewrite some unittest based on criterion
  lib/tests/CMakeLists.txt
  lib/tests/test_str_format.c
  lib/tests/test_userdb.c
  lib/tests/test_utf8utils.c
Labels: needs-review

#2046 Add debug message to program source/destination about successful start
  modules/afprog/afprog.c
Labels: needs-review

#2032 LogPipe: Improved debug logs
  lib/filter/filter-call.c
  lib/filter/filter-cmp.c
  lib/filter/filter-expr.c
  lib/filter/filter-expr.h
  lib/filter/filter-in-list.c
  lib/filter/filter-netmask.c
  lib/filter/filter-netmask6.c
  lib/filter/filter-pipe.c
  lib/filter/filter-pri.c
  lib/filter/filter-re.c
  lib/filter/filter-tags.c
  lib/logmsg/logmsg.c
  lib/logsource.c
  lib/parser/parser-expr.c
  lib/rewrite/rewrite-expr.c
  modules/add-contextual-data/add-contextual-data.c
  modules/csvparser/csvparser.c
  modules/date/date-parser.c
  modules/dbparser/dbparser.c
  modules/geoip/geoip-parser.c
  modules/geoip2/geoip-parser.c
  modules/json/json-parser.c
  modules/kvformat/kv-parser.c
  modules/map-value-pairs/map-value-pairs.c
  modules/python/python-logparser.c
  modules/snmptrapd-parser/snmptrapd-parser.c
  modules/syslogformat/syslog-parser.c
  modules/tagsparser/tags-parser.c
  modules/xml/xml.c
Labels: needs-review

#1923 dnscache: Disable the DNS cache if use-dns(no) is used
  lib/host-resolve.c
Labels: in progress

#2054 afsql: added ignore_tns_config sql config option
  modules/afsql/afsql-grammar.ym
  modules/afsql/afsql-parser.c
  modules/afsql/afsql.c
  modules/afsql/afsql.h
Labels: needs-review

#2049 secret-storage: add safer mem_zero()
  lib/control/control-commands.c
  lib/control/control-server.c
  lib/secret-storage/nondumpable-allocator.c
  lib/secret-storage/nondumpable-allocator.h
  lib/secret-storage/secret-storage.c
  lib/secret-storage/secret-storage.h
  lib/secret-storage/tests/test_nondumpable_allocator.c
  lib/secret-storage/tests/test_secret_storage.c
  syslog-ng-ctl/CMakeLists.txt
  syslog-ng-ctl/Makefile.am
  syslog-ng-ctl/syslog-ng-ctl.c
Labels: needs-review

#2059 Persistent stateful client-proto support
  lib/logproto/logproto-client.h
  modules/afsocket/afsocket-dest.c
Labels: in progress

#1952 Error reporting on misspelled block args
  lib/cfg-args.c
  lib/cfg-args.h
  lib/cfg-block-generator.c
  lib/cfg-block-generator.h
  lib/cfg-block.c
  lib/cfg-grammar.y
  lib/cfg-lex.l
  lib/cfg-lexer.c
  lib/cfg-tree.c
  modules/appmodel/app-parser-generator.c
  modules/appmodel/tests/test_app_parser_generator.c
  modules/confgen/confgen-plugin.c
  modules/system-source/system-source.c
  scl/default-network-drivers/plugin.conf
  scl/elasticsearch/plugin.conf
  scl/ewmm/ewmm.conf
  scl/graphite/plugin.conf
  scl/hdfs/plugin.conf
  scl/kafka/plugin.conf
  scl/loadbalancer/plugin.conf
  scl/loggly/loggly.conf
  scl/logmatic/logmatic.conf
  scl/nodejs/plugin.conf
  scl/osquery/plugin.conf
  scl/pacct/plugin.conf
  scl/snmptrap/snmptrapd-source.conf
Labels: needs-review

#1991 Fix connection close in network sources
  lib/logproto/logproto-server.c
  lib/logproto/logproto-server.h
  lib/logreader.c
  lib/logreader.h
  modules/afsocket/afsocket-source.c
Labels: in progress

#1992 LogReader async wakeup
  lib/logproto/logproto-buffered-server.c
  lib/logproto/logproto-buffered-server.h
  lib/logproto/logproto-framed-server.c
  lib/logproto/logproto-server.h
  lib/logproto/logproto-text-server.c
  lib/logreader.c
Labels: in progress

#2061 transport-factory-registry: overwriting of a factory instance is not …
  lib/transport/tests/test_transport_factory_registry.c
  lib/transport/transport-factory-registry.c
Labels: in progress

#2064 afsocket: add default_inet_port to protocol plugins
  lib/logproto/logproto-client.h
  lib/logproto/logproto-server.h
  modules/afsocket/afinet-dest.c
  modules/afsocket/afinet-source.c
  modules/afsocket/transport-mapper-inet.h
Labels: in progress

#2058 Rewrite test_reloc, test_scptid, test_cfg_tree based on criterion
  lib/tests/CMakeLists.txt
  lib/tests/test_cfg_tree.c
  lib/tests/test_rcptid.c
  lib/tests/test_reloc.c
Labels: in progress, needs-review

#2066 Small java code refactor
  modules/java/native/java_machine.c
  modules/java/native/java_machine.h
  modules/java/proxies/java-destination-proxy.c
  modules/java/proxies/java-logmsg-proxy.c
Labels: needs-review

#2068 debuggercli: remove getframe() hacks from completerlang
  modules/python/pylib/syslogng/debuggercli/completerlang.py
Labels: in progress

#2074 Fix loggen plugin handling
  configure.ac
  tests/loggen/loggen.c
  tests/loggen/socket_plugin/socket_plugin.c
  tests/loggen/ssl_plugin/ssl_plugin.c
Labels: in progress, needs-review

#2076 KW_FILE token in a global namespace
  lib/cfg-grammar.y
  lib/parser/parser-expr-parser.c
  modules/affile/affile-grammar.ym
  modules/dbparser/dbparser-grammar.ym
  modules/dbparser/dbparser-parser.c
Labels: needs-review

#2077 transport: extend TransportFactoryRegistry with remove() method
  lib/transport/tests/test_transport_factory_registry.c
  lib/transport/transport-factory-registry.c
  lib/transport/transport-factory-registry.h
Labels: in progress, needs-review
