Repository syslog-ng/syslog-ng, pull requests merged in 2018-11, with the labels that each got.

#2389 AFSocket: Make it possible to set the interface for socket.
  modules/afsocket/afsocket-grammar.ym
  modules/afsocket/afsocket-parser.c
  modules/afsocket/socket-options-inet.c
  modules/afsocket/socket-options-inet.h
Labels: user-visible-feature

#2386 Flush lines cleanup
  lib/cfg-grammar.y
  lib/cfg-parser.c
  lib/cfg.c
  lib/cfg.h
  lib/logthrdestdrv.c
  lib/logthrdestdrv.h
  lib/logwriter.c
  lib/logwriter.h
  lib/tests/test_logthrdestdrv.c
  modules/afsql/afsql-grammar.ym
  modules/http/http-grammar.ym
  modules/http/http-parser.c
  modules/http/http.c
  modules/http/http.h
  modules/riemann/riemann-grammar.ym
  modules/riemann/riemann-parser.c
  modules/riemann/riemann.c
Labels: user-visible-feature

#2416 Fix telegram dst default ca dir
  modules/http/http-grammar.ym
  modules/http/http-parser.c
  modules/http/http.c
  modules/http/http.h
  scl/telegram/telegram.conf
Labels: user-visible-feature

#2430 system-source: allow syslog-protocol on unix-dgram() sources
  modules/system-source/system-source.c
Labels: in progress

#2422 Rewrite filter unit tests based on criterion
  lib/filter/tests/CMakeLists.txt
  lib/filter/tests/Makefile.am
  lib/filter/tests/test_filters.c
  lib/filter/tests/test_filters_common.c
  lib/filter/tests/test_filters_common.h
  lib/filter/tests/test_filters_facility.c
  lib/filter/tests/test_filters_fop_cmp.c
  lib/filter/tests/test_filters_level_new.c
  lib/filter/tests/test_filters_netmask.c
  lib/filter/tests/test_filters_netmask6.c
  lib/filter/tests/test_filters_regexp.c
Labels: needs-review

#2425 internal source + trace level causes message storm
  lib/logsource.c
  lib/messages.c
  lib/messages.h
Labels: needs-review

#2372 tls: disable ssl compression by default
  lib/tlscontext.c
  lib/tlscontext.h
  lib/transport/transport-factory-tls.c
  lib/transport/transport-factory-tls.h
  modules/afsocket/afsocket-grammar.ym
  modules/afsocket/afsocket-parser.c
  modules/afsocket/transport-mapper-inet.c
  modules/afsocket/transport-mapper-inet.h
Labels: needs-review, user-visible-feature

#2432 Fix frequent disconnects of syslog() with TLS
  lib/logproto/logproto-framed-server.c
  lib/logproto/tests/test-framed-server.c
  modules/afsocket/afinet-dest.c
Labels: needs-review
