Repository syslog-ng/syslog-ng, pull requests merged in 2018-07, with the labels that each got.

#2169 Extended Linux capabilities detection (pkg-config)
  configure.ac
Labels: needs-review

#2170 FreeBSD 11.2 builderror SOCK_STREAM
  tests/loggen/ssl_plugin/ssl_plugin.c
Labels: needs-review

#2175 csv_parser test: revwrite based on criterion
  modules/csvparser/tests/CMakeLists.txt
  modules/csvparser/tests/test_csvparser.c
Labels: needs-review

#2167 Fix suspend race cond
  lib/CMakeLists.txt
  lib/Makefile.am
  lib/early_ack_tracker.c
  lib/late_ack_tracker.c
  lib/logsource.c
  lib/logsource.h
  lib/tests/CMakeLists.txt
  lib/tests/Makefile.am
  lib/tests/test_window_size_counter.c
  lib/window-size-counter.c
  lib/window-size-counter.h
Labels: in progress

#2164 Once java always java
  modules/java/native/java_machine.c
  modules/java/tools/syslog-ng.conf.example
Labels: in progress

#2181 scl/cim: add requires json-plugin
  scl/cim/adapter.conf
Labels: in progress

#2182 Make g_atomic_counter_set() atomic and update minimum glib version to 2.26
  CMakeLists.txt
  configure.ac
  lib/atomic.h
  lib/compat/glib.h
Labels: needs-review

#2186 New linux-audit() source as SCL
  scl/linux-audit/linux-audit.conf
Labels: in progress

#2174 Fix padding template function
  modules/basicfuncs/str-funcs.c
  modules/basicfuncs/tests/test_basicfuncs.c
Labels: in progress

#2166 system-source: added exclude_kmsg option instead of container detection
  lib/cfg-args.c
  lib/cfg-args.h
  modules/system-source/system-source.c
Labels: in progress

#2185 WildcardFileReader: the callback registration mechanism is refactored
  modules/affile/tests/test_wildcard_file_reader.c
  modules/affile/wildcard-file-reader.c
  modules/affile/wildcard-file-reader.h
  modules/affile/wildcard-source.c
  modules/affile/wildcard-source.h
Labels: in progress

#2193 Minor stats-query fixes and refactor
  lib/stats/stats-cluster.c
  lib/stats/stats-counter.c
  lib/stats/stats-counter.h
  lib/stats/stats-query-commands.c
  lib/stats/stats-query.c
  lib/stats/stats-query.h
  lib/stats/tests/test_stats_query.c
Labels: needs-review

#2168 afsocket: Add ref-counted TLSVerifier struct
  lib/tlscontext.c
  lib/tlscontext.h
  lib/transport/transport-factory-tls.c
  lib/transport/transport-factory-tls.h
  modules/afsocket/afinet-dest.c
  modules/afsocket/afinet-source.c
  modules/afsocket/tests/test-transport-mapper-inet.c
  modules/afsocket/transport-mapper-inet.c
  modules/afsocket/transport-mapper-inet.h
Labels: community-driven-merge

#2063 LogThreadedDestDriver batching
  Makefile.am
  lib/cfg-tree.c
  lib/control/control-main.c
  lib/control/control-main.h
  lib/logpipe.h
  lib/logthrdestdrv.c
  lib/logthrdestdrv.h
  lib/mainloop-worker.c
  lib/mainloop-worker.h
  lib/mainloop.c
  lib/mainloop.h
  lib/stats/stats-counter.h
  lib/tests/CMakeLists.txt
  lib/tests/Makefile.am
  lib/tests/test_logthrdestdrv.c
  libtest/grab-logging.c
  libtest/grab-logging.h
  libtest/stopwatch.c
  libtest/stopwatch.h
  modules/afamqp/afamqp.c
  modules/afmongodb/afmongodb.c
  modules/afmongodb/tests/test-mongodb-config.c
  modules/afsmtp/afsmtp.c
  modules/afsql/afsql.c
  modules/afstomp/afstomp.c
  modules/diskq/tests/Makefile.am
  modules/http/http.c
  modules/java/native/java-destination.c
  modules/python/python-dest.c
  modules/redis/redis.c
  modules/riemann/riemann.c
Labels: in progress

#2192 Reliable disk buffer non-empty backlog
  modules/diskq/diskq-options.c
  modules/diskq/diskq.c
  modules/diskq/logqueue-disk-non-reliable.c
  modules/diskq/logqueue-disk-reliable.c
  modules/diskq/qdisk.c
  modules/diskq/qdisk.h
  modules/diskq/tests/test_reliable_backlog.c
Labels: in progress

#2204 client-lib-dir, loggen, eventlog: minor fixes
  lib/eventlog/src/evtlog.h
  lib/eventlog/src/evttags.c
  scl/elasticsearch/plugin.conf
  scl/hdfs/plugin.conf
  scl/kafka/plugin.conf
  tests/loggen/loggen_helper.c
Labels: in progress

#2188 dbld: fix pip package versions on older Distro releases
  .travis.yml
  dbld/images/required-apt/all.txt
  dbld/images/required-apt/stretch.txt
  dbld/images/required-obs/stretch.txt
  dbld/images/required-pip/all.txt
  dbld/images/required-pip/artful.txt
  dbld/images/required-pip/centos6.txt
  dbld/images/required-pip/centos7.txt
  dbld/images/required-pip/devshell.txt
  dbld/images/required-pip/jessie.txt
  dbld/images/required-pip/stretch.txt
  dbld/images/required-pip/trusty.txt
  dbld/images/required-pip/xenial.txt
  dbld/images/stretch.dockerfile
  requirements.txt
Labels: in progress

#2208 sudo: filter out incorrectly parsed logs
  scl/sudo/sudo.conf
Labels: in progress

#2210 Dbld add sqlite3 and riemann to devshell
  dbld/images/devshell-apt/all.txt
Labels: in progress

#2209 scl/ewmm: rename syslog-ng() source to ewmm()
  scl/ewmm/ewmm.conf
Labels: in progress

#2211 java: warning message correction
  modules/java/native/java_machine.c
Labels: in progress
