Repository syslog-ng/syslog-ng, pull requests merged in 2019-02, with the labels that each got.

#2511 Add persist-tool
  CMakeLists.txt
  Makefile.am
  lib/persist-state.c
  lib/persist-state.h
  persist-tool/CMakeLists.txt
  persist-tool/Makefile.am
  persist-tool/add.c
  persist-tool/add.h
  persist-tool/dump.c
  persist-tool/dump.h
  persist-tool/generate.c
  persist-tool/generate.h
  persist-tool/persist-tool.c
  persist-tool/persist-tool.h
  tests/copyright/policy
Labels: needs-review, user-visible-feature

#2459 Split xml-parser into xml-parser and xml-scanner
  lib/CMakeLists.txt
  lib/Makefile.am
  lib/scanner/CMakeLists.txt
  lib/scanner/xml-scanner/CMakeLists.txt
  lib/scanner/xml-scanner/Makefile.am
  lib/scanner/xml-scanner/tests/CMakeLists.txt
  lib/scanner/xml-scanner/tests/Makefile.am
  lib/scanner/xml-scanner/tests/test_xml_scanner.c
  lib/scanner/xml-scanner/xml-scanner.c
  lib/scanner/xml-scanner/xml-scanner.h
  modules/xml/tests/test_xml_parser.c
  modules/xml/xml-grammar.ym
  modules/xml/xml.c
  modules/xml/xml.h
  tests/copyright/policy
Labels: in progress, user-visible-feature

#2536 Json list support
  lib/scanner/list-scanner/list-scanner.c
  lib/scanner/list-scanner/list-scanner.h
  lib/scanner/list-scanner/tests/test_list_scanner.c
  lib/type-hinting.c
  lib/type-hinting.h
  modules/json/format-json.c
  modules/json/tests/test_format_json.c
Labels: user-visible-feature

#2554 Remove elastic v1 support
  doc/man/syslog-ng.conf.5.xml
  modules/java-modules/Makefile.am
  modules/java-modules/elastic/build.gradle
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/ElasticSearchDestination.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/ElasticSearchOptions.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/client/ESClient.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/client/ESClientFactory.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/client/ESNodeClient.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/client/ESTransportClient.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/client/UnknownESClientModeException.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/messageprocessor/DummyProcessor.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/messageprocessor/ESBulkMessageProcessor.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/messageprocessor/ESMessageProcessor.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/messageprocessor/ESMessageProcessorFactory.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/messageprocessor/ESSingleMessageProcessor.java
  modules/java-modules/settings.gradle
  modules/java/README.md
  packaging/debian/syslog-ng-mod-elastic.install
  scl/elasticsearch/plugin.conf
  tests/copyright/policy
Labels: user-visible-feature

#2541 scl: add parser for netskope logs
  packaging/debian/syslog-ng-core.install
  scl/CMakeLists.txt
  scl/Makefile.am
  scl/netskope/plugin.conf
Labels: user-visible-feature

#2559 python, java destination add already introduced retry
  modules/java/src/main/java/org/syslog_ng/LogDestination.java
  modules/python/python-dest.c
  modules/python/sngexample.py
Labels: user-visible-feature

#2565 improvements in example-msg-generator
  modules/examples/sources/msg-generator/msg-generator-grammar.ym
  modules/examples/sources/msg-generator/msg-generator-parser.c
  modules/examples/sources/msg-generator/msg-generator-source-options.h
  modules/examples/sources/msg-generator/msg-generator-source.c
Labels: user-visible-feature

#2538 xml/geoip2: make prefix optional
  lib/scanner/xml-scanner/tests/test_xml_scanner.c
  lib/scanner/xml-scanner/xml-scanner.c
  modules/geoip2/geoip-parser.c
  modules/geoip2/tests/test_geoip_parser.c
  modules/xml/tests/test_xml_parser.c
  modules/xml/xml.c
Labels: user-visible-feature

#2413 Custom LGTM.com query for detecting uses of gmtime that are not covered by a lock
  .lgtm.yml
  .lgtm/cpp-queries/call-to-gmtime-without-lock.ql
Labels: needs-review

#2543 Pytest: Added minor fixes
  tests/python_functional/conftest.py
  tests/python_functional/src/common/blocking.py
  tests/python_functional/src/common/operations.py
  tests/python_functional/src/message_builder/bsd_format.py
  tests/python_functional/src/message_builder/log_message.py
  tests/python_functional/src/setup/testcase.py
  tests/python_functional/src/setup/testcase_parameters.py
  tests/python_functional/src/setup/tests/__init__.py
  tests/python_functional/src/setup/tests/test_testcase_parameters.py
  tests/python_functional/src/setup/unit_testcase.py
  tests/python_functional/src/syslog_ng/console_log_reader.py
  tests/python_functional/src/syslog_ng/syslog_ng.py
  tests/python_functional/src/syslog_ng/syslog_ng_cli.py
  tests/python_functional/src/syslog_ng/syslog_ng_paths.py
  tests/python_functional/src/syslog_ng/tests/test_syslog_ng_paths.py
  tests/python_functional/src/syslog_ng_config/renderer.py
  tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
Labels: needs-review

#2567 format nonliteral fixes
  lib/logmsg/tests/test_log_message.c
  modules/afsmtp/afsmtp.c
  modules/diskq/qdisk.c
  modules/stardate/stardate.c
Labels: community-driven-merge
