Repository syslog-ng/syslog-ng, pull requests merged in 2019-08, with the labels that each got.

#2855 Dqtool relocate diskq
  lib/persist-state.c
  modules/diskq/dqtool.c
Labels: enhancement, user-visible-feature

#2868 few small fries leak fixed
  lib/cfg.c
  lib/logmsg/nvhandle-descriptors.c
  lib/logmsg/nvhandle-descriptors.h
  lib/logmsg/nvtable.c
  lib/secret-storage/tests/test_secret_storage.c
Labels: easy

#2797 cfg-grammar: add new path type for files
  lib/CMakeLists.txt
  lib/Makefile.am
  lib/cfg-grammar.y
  lib/cfg-lexer.h
  lib/cfg-path.c
  lib/cfg-path.h
  lib/cfg.c
  lib/cfg.h
  lib/control/control-server.c
  lib/control/tests/test_control_cmds.c
  lib/mainloop-control.c
  modules/add-contextual-data/add-contextual-data-grammar.ym
  modules/afamqp/afamqp-grammar.ym
  modules/afsocket/afsocket-grammar.ym
  modules/dbparser/dbparser-grammar.ym
  modules/geoip/geoip-parser-grammar.ym
  modules/geoip2/geoip-parser-grammar.ym
  modules/http/http-grammar.ym
  modules/kafka/kafka-grammar.ym
  modules/pseudofile/pseudofile-grammar.ym
  modules/riemann/riemann-grammar.ym
  syslog-ng-ctl/syslog-ng-ctl.c
Labels: community-driven-merge, user-visible-feature

#2869 cfg parsing: read config file into memory + preprocess-into to stdout
  lib/cfg-lexer.c
  lib/cfg-lexer.h
  lib/cfg.c
Labels: user-visible-feature

#2894 templates: change the $LOGHOST macro to honour use-fqdn()
  lib/template/macros.c
  lib/template/templates.c
  lib/template/templates.h
  lib/template/tests/test_template.c
Labels: user-visible-feature
