Repository syslog-ng/syslog-ng, pull requests merged in 2019-01, with the labels that each got.

#2477 loggen: paramter handling
  tests/loggen/loggen.c
  tests/loggen/socket_plugin/socket_plugin.c
  tests/loggen/ssl_plugin/ssl_plugin.c
Labels: in progress

#2481 pytest-framework: fix travis failure
  .travis.yml
  requirements.txt
Labels: in progress

#2475 syslog-ng.8.xml: remove unneeded default-modules section
  doc/man/syslog-ng.8.xml
Labels: community-driven-merge

#2441 PytestPART2: MessageBuilder updates
  tests/pytest_framework/functional_tests/source_drivers/file_source/test_acceptance.py
  tests/pytest_framework/src/message_builder/bsd_format.py
  tests/pytest_framework/src/message_builder/log_message.py
  tests/pytest_framework/src/setup/testcase.py
Labels: in progress

#2455 cfg-parser: printing error positions in case of parse failure
  lib/cfg-parser.c
Labels: in progress

#2442 PytestPART3: SyslogNgCli updates
  tests/pytest_framework/conftest.py
  tests/pytest_framework/src/setup/testcase.py
  tests/pytest_framework/src/setup/testcase_parameters.py
  tests/pytest_framework/src/setup/tests/test_testcase_parameters.py
  tests/pytest_framework/src/setup/unit_testcase.py
  tests/pytest_framework/src/syslog_ng/console_log_reader.py
  tests/pytest_framework/src/syslog_ng/syslog_ng.py
  tests/pytest_framework/src/syslog_ng/syslog_ng_cli.py
  tests/pytest_framework/src/syslog_ng/syslog_ng_executor.py
  tests/pytest_framework/src/syslog_ng/syslog_ng_paths.py
  tests/pytest_framework/src/syslog_ng/tests/test_syslog_ng_paths.py
Labels: in progress

#2471 Websense parser
  lib/rewrite/rewrite-subst.c
  packaging/debian/syslog-ng-core.install
  scl/CMakeLists.txt
  scl/Makefile.am
  scl/websense/plugin.conf
Labels: needs-review, user-visible-feature

#2485 Pytest: Added minor fixes to unittest
  tests/pytest_framework/src/logger/logger.py
  tests/pytest_framework/src/setup/unit_testcase.py
Labels: needs-review

#2482 lib/compat: replace strcasestr() implementation
  .astylerc
  lib/compat/strcasestr.c
Labels: in progress

#2489 syslog-ng@default: use pid file location on control socket
  contrib/systemd/syslog-ng@default
Labels: community-driven-merge

#2487 python-destination: send can return worker_insert_result_t, flush support
  lib/logthrdestdrv.h
  modules/python/compat/compat-python-v2.c
  modules/python/compat/compat-python-v3.c
  modules/python/compat/compat-python.h
  modules/python/python-dest.c
Labels: in progress, user-visible-feature

#2490 pytest_framework: support for implicit groups in config.create_logpath
  tests/pytest_framework/functional_tests/config_change/test_manipulating_config_between_reload.py
  tests/pytest_framework/functional_tests/logpath/test_flags_catch_all.py
  tests/pytest_framework/functional_tests/logpath/test_flags_fallback.py
  tests/pytest_framework/functional_tests/logpath/test_flags_final.py
  tests/pytest_framework/functional_tests/logpath/test_multiple_embedded_logpaths.py
  tests/pytest_framework/functional_tests/logpath/test_multiple_flags.py
  tests/pytest_framework/functional_tests/source_drivers/file_source/test_acceptance.py
  tests/pytest_framework/src/syslog_ng_config/renderer.py
  tests/pytest_framework/src/syslog_ng_config/statement_group.py
  tests/pytest_framework/src/syslog_ng_config/statements/destinations/destination_driver.py
  tests/pytest_framework/src/syslog_ng_config/statements/filters/filter.py
  tests/pytest_framework/src/syslog_ng_config/statements/logpath/logpath.py
  tests/pytest_framework/src/syslog_ng_config/statements/sources/source_driver.py
  tests/pytest_framework/src/syslog_ng_config/syslog_ng_config.py
Labels: in progress

#2493 pytest_framework: timeout parameter for wait_until_true
  tests/pytest_framework/src/common/blocking.py
  tests/pytest_framework/src/common/tests/test_blocking.py
  tests/pytest_framework/src/message_reader/message_reader.py
  tests/pytest_framework/src/message_reader/tests/test_message_reader.py
Labels: in progress

#2492 pytest_framework: faster failure detection for semantically invalid configs
  tests/pytest_framework/src/syslog_ng/syslog_ng_cli.py
  tests/pytest_framework/src/syslog_ng_ctl/syslog_ng_ctl.py
  tests/pytest_framework/src/syslog_ng_ctl/syslog_ng_ctl_cli.py
Labels: in progress

#2505 python: internal() source exposed via syslogng.Logger
  modules/python/CMakeLists.txt
  modules/python/Makefile.am
  modules/python/python-logger.c
  modules/python/python-logger.h
  modules/python/python-plugin.c
Labels: needs-review, user-visible-feature

#2468 ProtoClient: provide process_in function to logwriter
  lib/logproto/logproto-client.c
  lib/logproto/logproto-client.h
  lib/logproto/logproto-text-client.c
  lib/logreader.c
  lib/logwriter.c
  lib/mainloop-io-worker.c
  lib/mainloop-io-worker.h
  modules/afsocket/afsocket-dest.c
  modules/afsocket/afsocket-dest.h
  modules/afsocket/afsocket-grammar.ym
  modules/afsocket/afsocket-parser.c
  modules/systemd-journal/journal-reader.c
Labels: needs-review

#2506 simpler names for WORKER_INSERT_RESULT_T in language bindings
  lib/logthrdestdrv.c
  lib/logthrdestdrv.h
  lib/tests/test_logthrdestdrv.c
  modules/afamqp/afamqp.c
  modules/afmongodb/afmongodb.c
  modules/afsmtp/afsmtp.c
  modules/afsql/afsql.c
  modules/afstomp/afstomp.c
  modules/http/http-worker.c
  modules/http/http-worker.h
  modules/http/tests/test_http.c
  modules/java-modules/dummy/src/main/java/org/syslog_ng/DummyTextDestination.java
  modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/ElasticSearchDestination.java
  modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/ElasticSearchDestination.java
  modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsDestination.java
  modules/java-modules/http/src/main/java/org/syslog_ng/http/HTTPDestination.java
  modules/java-modules/kafka/src/main/java/org/syslog_ng/KafkaDestination.java
  modules/java/native/java-destination.c
  modules/java/src/main/java/org/syslog_ng/DummyStructuredDestination.java
  modules/java/src/main/java/org/syslog_ng/DummyTextDestination.java
  modules/java/src/main/java/org/syslog_ng/LogDestination.java
  modules/java/src/main/java/org/syslog_ng/StructuredLogDestination.java
  modules/java/src/main/java/org/syslog_ng/TextLogDestination.java
  modules/python/python-dest.c
  modules/python/sngexample.py
  modules/redis/redis.c
  modules/riemann/riemann-worker.c
Labels: user-visible-feature
