Repository syslog-ng/syslog-ng, pull requests merged in 2019-05, with the labels that each got.

#2676 amqp: heartbeat support
  modules/afamqp/afamqp-grammar.ym
  modules/afamqp/afamqp-parser.c
  modules/afamqp/afamqp.c
  modules/afamqp/afamqp.h
Labels: community-driven-merge, user-visible-feature

#2496 Rdkafka destination
  .travis.yml
  cmake/Modules/Findrdkafka.cmake
  configure.ac
  dbld/images/helpers/dependencies.sh
  dbld/images/helpers/packages.manifest
  dbld/images/ubuntu-bionic.dockerfile
  lib/cfg-grammar.y
  lib/cfg-lex.l
  lib/stats/stats-cluster.c
  lib/stats/stats-cluster.h
  modules/CMakeLists.txt
  modules/Makefile.am
  modules/diskq/logqueue-disk-non-reliable.c
  modules/kafka/CMakeLists.txt
  modules/kafka/Makefile.am
  modules/kafka/README.md
  modules/kafka/kafka-dest-driver.c
  modules/kafka/kafka-dest-driver.h
  modules/kafka/kafka-dest-worker.c
  modules/kafka/kafka-dest-worker.h
  modules/kafka/kafka-grammar.ym
  modules/kafka/kafka-parser.c
  modules/kafka/kafka-parser.h
  modules/kafka/kafka-plugin.c
  modules/kafka/kafka-props.c
  modules/kafka/kafka-props.h
  modules/kafka/tests/CMakeLists.txt
  modules/kafka/tests/Makefile.am
  modules/kafka/tests/sample.properties
  modules/kafka/tests/test_kafka-props.c
  scl/kafka/plugin.conf
  tests/copyright/policy
Labels: user-visible-feature

#2700 Add implode and explode template functions
  modules/basicfuncs/basic-funcs.c
  modules/basicfuncs/list-funcs.c
  modules/basicfuncs/tests/test_basicfuncs.c
Labels: user-visible-feature

#2709 Add support for usec precision when parsing time
  lib/timeutils/CMakeLists.txt
  lib/timeutils/Makefile.am
  lib/timeutils/strptime-tz.c
  lib/timeutils/strptime-tz.h
  lib/timeutils/tests/test_wallclocktime.c
  lib/timeutils/wallclocktime.c
Labels: community-driven-merge, user-visible-feature

#2693 Snmp destination
  .travis.yml
  CMakeLists.txt
  cmake/Modules/FindNetSnmp.cmake
  configure.ac
  dbld/images/helpers/packages.manifest
  modules/CMakeLists.txt
  modules/Makefile.am
  modules/snmp-dest/CMakeLists.txt
  modules/snmp-dest/Makefile.am
  modules/snmp-dest/snmpdest-grammar.ym
  modules/snmp-dest/snmpdest-parser.c
  modules/snmp-dest/snmpdest-parser.h
  modules/snmp-dest/snmpdest-plugin.c
  modules/snmp-dest/snmpdest.c
  modules/snmp-dest/snmpdest.h
  modules/snmp-dest/tests/CMakeLists.txt
  modules/snmp-dest/tests/Makefile.am
  modules/snmp-dest/tests/test_snmp_dest.c
  packaging/debian/control
  packaging/debian/rules
  packaging/debian/syslog-ng-mod-snmp.install
  tests/copyright/policy
Labels: needs-review, user-visible-feature

#2737 SNMP destination: build-related fixes
  configure.ac
  modules/Makefile.am
  modules/snmp-dest/CMakeLists.txt
  modules/snmp-dest/Makefile.am
  modules/snmp-dest/tests/CMakeLists.txt
  packaging/debian/control
Labels: in progress

#2731 Debug mode does not imply stderr
  syslog-ng/main.c
Labels: in progress

#2691 Reset the timezone on config reload event.
  lib/timeutils/misc.c
  lib/timeutils/misc.h
  syslog-ng/main.c
Labels: community-driven-merge

#2716 $(template) dynamic binding
  lib/template/templates.c
  lib/template/templates.h
  libtest/cr_template.c
  modules/basicfuncs/basic-funcs.c
  modules/basicfuncs/str-funcs.c
  modules/basicfuncs/tests/test_basicfuncs.c
  modules/basicfuncs/tf-template.c
Labels: user-visible-feature

#2715 Template support in match
  lib/filter/filter-expr-grammar.ym
  lib/filter/filter-re.c
  lib/filter/filter-re.h
  lib/filter/tests/CMakeLists.txt
  lib/filter/tests/test_filters_common.c
  lib/filter/tests/test_filters_common.h
  lib/filter/tests/test_filters_regexp.c
  lib/rewrite/rewrite-subst.c
  scl/apache/apache.conf
  scl/cisco/plugin.conf
Labels: user-visible-feature
