Repository syslog-ng/syslog-ng, pull requests merged in 2019-03, with the labels that each got.

#2546 light: Switch to native logger
  dbld/images/helpers/pip_packages.manifest
  tests/copyright/policy
  tests/python_functional/conftest.py
  tests/python_functional/pytest.ini
  tests/python_functional/src/driver_io/file/file.py
  tests/python_functional/src/driver_io/file/file_io.py
  tests/python_functional/src/driver_io/file/tests/test_file_io.py
  tests/python_functional/src/executors/command_executor.py
  tests/python_functional/src/executors/process_executor.py
  tests/python_functional/src/executors/tests/test_command_executor.py
  tests/python_functional/src/executors/tests/test_process_executor.py
  tests/python_functional/src/logger/__init__.py
  tests/python_functional/src/logger/logger.py
  tests/python_functional/src/logger/logger_factory.py
  tests/python_functional/src/logger/tests/__init__.py
  tests/python_functional/src/logger/tests/test_logger.py
  tests/python_functional/src/logger/tests/test_logger_factory.py
  tests/python_functional/src/message_reader/message_reader.py
  tests/python_functional/src/message_reader/single_line_parser.py
  tests/python_functional/src/message_reader/tests/test_message_reader.py
  tests/python_functional/src/message_reader/tests/test_single_line_parser.py
  tests/python_functional/src/setup/testcase.py
  tests/python_functional/src/setup/testcase_parameters.py
  tests/python_functional/src/setup/unit_testcase.py
  tests/python_functional/src/syslog_ng/console_log_reader.py
  tests/python_functional/src/syslog_ng/syslog_ng.py
  tests/python_functional/src/syslog_ng/syslog_ng_cli.py
  tests/python_functional/src/syslog_ng/syslog_ng_executor.py
  tests/python_functional/src/syslog_ng_config/statements/destinations/destination_driver.py
  tests/python_functional/src/syslog_ng_config/statements/destinations/file_destination.py
  tests/python_functional/src/syslog_ng_config/statements/filters/filter.py
  tests/python_functional/src/syslog_ng_config/statements/sources/file_source.py
  tests/python_functional/src/syslog_ng_config/statements/sources/source_driver.py
  tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
  tests/python_functional/src/syslog_ng_ctl/syslog_ng_ctl.py
  tests/python_functional/src/syslog_ng_ctl/syslog_ng_ctl_cli.py
  tests/python_functional/src/syslog_ng_ctl/syslog_ng_ctl_executor.py
Labels: needs-review

#2594 test_filters: rewrite test cases in criterion
  lib/filter/tests/CMakeLists.txt
  lib/filter/tests/test_filters_in_list.c
Labels: community-driven-merge

#2519 value-pairs: add an --omit-empty-values option
  lib/value-pairs/cmdline.c
  lib/value-pairs/value-pairs.c
  lib/value-pairs/value-pairs.h
  libtest/cr_template.c
  modules/json/tests/test_format_json.c
Labels: user-visible-feature

#2591 test_template_compile: rewrite test cases in criterion
  lib/template/tests/CMakeLists.txt
  lib/template/tests/test_template_compile.c
Labels: community-driven-merge

#2599 test_cfg_lexer_subst: rewrite test cases in criterion
  lib/tests/CMakeLists.txt
  lib/tests/test_cfg_lexer_subst.c
Labels: community-driven-merge

#2509 Added elasticsearch-http() destination
  scl/elasticsearch/elastic-http.conf
Labels: user-visible-feature

#2616 test_host_resolve: rewrite test cases in criterion
  lib/tests/test_host_resolve.c
Labels: community-driven-merge

#2618 test_encode: rewrite test cases in criterion
  lib/str-repr/tests/CMakeLists.txt
  lib/str-repr/tests/test_encode.c
Labels: community-driven-merge

#2593 test_timestamp_serialize: rewrite test cases in criterion
  lib/logmsg/tests/CMakeLists.txt
  lib/logmsg/tests/test_timestamp_serialize.c
Labels: community-driven-merge

#2626 afamqp: add support for external authentication
  modules/afamqp/afamqp-grammar.ym
  modules/afamqp/afamqp-parser.c
  modules/afamqp/afamqp.c
  modules/afamqp/afamqp.h
Labels: community-driven-merge, user-visible-feature

#2535 afinet: add option to set the maximum spoofed datagram size
  modules/afsocket/afinet-dest.c
  modules/afsocket/afinet-dest.h
  modules/afsocket/afsocket-grammar.ym
  modules/afsocket/afsocket-parser.c
Labels: user-visible-feature
