Repository syslog-ng/syslog-ng, pull requests merged in 2019-09, with the labels that each got.

#2878 template: isoweek support
  lib/template/macros.c
  lib/template/macros.h
  lib/template/tests/CMakeLists.txt
  lib/template/tests/Makefile.am
  lib/template/tests/test_macro.c
  lib/timeutils/wallclocktime.c
  lib/timeutils/wallclocktime.h
  lib/value-pairs/tests/test_value_pairs.c
Labels: user-visible-feature

#2872 Dqtool assign to persist
  CMakeLists.txt
  configure.ac
  lib/compat/glib.c
  lib/compat/glib.h
  modules/diskq/dqtool.c
  syslog-ng-config.h.in
Labels: support-tool

#2902 various refactor, build issue fixes
  cmake/Makefile.am
  cmake/Modules/FindLIBCAP.cmake
  cmake/Modules/FindLibNet.cmake
  cmake/Modules/FindResolv.cmake
  configure.ac
  lib/CMakeLists.txt
  lib/compat/string.h
  modules/afsocket/CMakeLists.txt
  modules/afsql/CMakeLists.txt
  modules/confgen/tests/Makefile.am
  modules/cryptofuncs/CMakeLists.txt
  tests/loggen/CMakeLists.txt
  tests/loggen/Makefile.am
  tests/loggen/ssl_plugin/CMakeLists.txt
  tests/python_functional/Makefile.am
Labels: compile related, refactor

#2890 add format-flat-json template function
  modules/json/format-json.c
  modules/json/format-json.h
  modules/json/json-plugin.c
  modules/json/tests/test_format_json.c
Labels: user-visible-feature

#2870 filter: small refactors
  lib/filter/filter-cmp.c
  lib/filter/filter-re.c
Labels: needs-review, refactor

#2930 tls: add SNI support
  lib/tlscontext.c
  lib/tlscontext.h
  modules/afsocket/afsocket-grammar.ym
  modules/afsocket/afsocket-parser.c
Labels: user-visible-feature

#2780 geoip: remove deprecated module, geoip2 database location detection
  cmake/Makefile.am
  cmake/Modules/FindLibGeoIP.cmake
  configure.ac
  dbld/images/helpers/packages.manifest
  modules/CMakeLists.txt
  modules/Makefile.am
  modules/geoip/CMakeLists.txt
  modules/geoip/Makefile.am
  modules/geoip/geoip-helper.c
  modules/geoip/geoip-helper.h
  modules/geoip/geoip-parser-grammar.ym
  modules/geoip/geoip-parser-parser.c
  modules/geoip/geoip-parser-parser.h
  modules/geoip/geoip-parser.c
  modules/geoip/geoip-parser.h
  modules/geoip/geoip-plugin.c
  modules/geoip/tests/CMakeLists.txt
  modules/geoip/tests/Makefile.am
  modules/geoip/tests/test_geoip_parser.c
  modules/geoip/tfgeoip.c
  modules/geoip2/geoip-parser.c
  modules/geoip2/maxminddb-helper.c
  modules/geoip2/maxminddb-helper.h
  modules/geoip2/tfgeoip.c
  modules/python/pylib/syslogng/debuggercli/syslognginternals.py
  modules/python/pylib/syslogng/debuggercli/tests/test_tflang.py
  modules/python/pylib/syslogng/debuggercli/tflang.py
  packaging/debian/Makefile.am
  packaging/debian/control
  packaging/debian/copyright
  packaging/debian/tests/control
  packaging/debian/tests/upgrade
  packaging/rhel/syslog-ng.spec
  tests/copyright/policy
Labels: user-visible-feature
