Repository syslog-ng/syslog-ng, pull requests merged in 2019-04, with the labels that each got.

#2621 test_diskq: rewrite test cases in criterion
  modules/diskq/tests/CMakeLists.txt
  modules/diskq/tests/test_diskq.c
  modules/diskq/tests/test_diskq_full.c
  modules/diskq/tests/test_diskq_truncate.c
  modules/diskq/tests/test_reliable_backlog.c
Labels: community-driven-merge

#2644 Trim large messages
  lib/cfg-grammar.y
  lib/cfg-parser.c
  lib/cfg.h
  lib/logproto/logproto-framed-server.c
  lib/logproto/logproto-server.c
  lib/logproto/logproto-server.h
  lib/logproto/tests/test-framed-server.c
Labels: user-visible-feature

#2657 graylog2 support tls, udp
  scl/graylog2/plugin.conf
Labels: user-visible-feature

#2669 Fix unit test with function pointer dereference in case of ASLR, Criterion
  modules/diskq/tests/test_diskq.c
Labels: compile related

#2671 cfg-parser: add aliases for yesno
  lib/cfg-grammar.y
  lib/cfg-parser.c
  lib/cfg-parser.h
  modules/appmodel/app-parser-generator.c
Labels: user-visible-feature

#2619 test_systemd_journal: rewrite test cases in criterion
  modules/systemd-journal/tests/CMakeLists.txt
  modules/systemd-journal/tests/test-source.c
  modules/systemd-journal/tests/test_systemd_journal.c
Labels: community-driven-merge

#2673 Date parser to support guess timezone
  modules/date/date-grammar.ym
  modules/date/date-parser.c
  modules/date/date-parser.h
  modules/date/tests/test_date.c
Labels: user-visible-feature

#2664 patterndb: Add sort option to pdbtool merge
  modules/dbparser/pdb-file.c
  modules/dbparser/pdb-file.h
  modules/dbparser/pdbtool/pdbtool.c
  modules/dbparser/tests/test_patterndb.c
Labels: user-visible-feature

#2688 support for vhost:port in common/combined log formats
  scl/apache/apache.conf
Labels: community-driven-merge
