Repository syslog-ng/syslog-ng, pull requests merged in 2019-10, with the labels that each got.

#2961 scl/default-network-drivers: add max-connections
  scl/default-network-drivers/plugin.conf
Labels: community-driven-merge, user-visible-feature

#2968 Updated Quickstart link
  README.md
Labels: community-driven-merge

#2943 balabit/syslog-ng -> syslog-ng/syslog-ng transition
  CONTRIBUTING.md
  README.md
  lib/str-utils.c
  modules/java/Makefile.am
  packaging/debian/copyright
  packaging/debian/watch
  packaging/rhel/syslog-ng.spec
  scl/system/plugin.conf
  tests/valgrind/unit-test-leak.supp
Labels: user-visible-feature

#2970 dbld: fix OS_PLATFORM value in devshell images
  dbld/images/devshell.dockerfile
Labels: compile related, user-visible-feature

#2992 Add disable jit flag to logmatcher
  lib/logmatcher.c
  lib/logmatcher.h
  tests/unit/test_matcher.c
Labels: user-visible-feature
