Repository syslog-ng/syslog-ng, pull requests merged in 2020-11, with the labels that each got.

#3474 option truncating logwriter based destination msg payload size
  lib/cfg-grammar.y
  lib/cfg-parser.c
  lib/logwriter.c
  lib/logwriter.h
  modules/afsocket/afinet-dest.c
  news/bugfix-3474.md
  news/feature-3474.md
  tests/unit/test_logwriter.c
Labels: user-visible-feature

#3453 date-parser: extend %z to support time zones other then local and gmt
  lib/timeutils/wallclocktime.c
  modules/timestamp/tests/test_date.c
  news/bugfix-3453.md
  news/feature-3453.md
Labels: user-visible-feature

#3480 Version: 3.30.1
  NEWS.md
  README.md
  VERSION
  contrib/openbsd-packaging/syslog-ng.conf
  doc/man/dqtool.1.xml
  doc/man/loggen.1.xml
  doc/man/pdbtool.1.xml
  doc/man/persist-tool.1.xml
  doc/man/secure-logging.7.xml
  doc/man/slogencrypt.1.xml
  doc/man/slogkey.1.xml
  doc/man/slogverify.1.xml
  doc/man/syslog-ng-ctl.1.xml
  doc/man/syslog-ng-debun.1.xml
  doc/man/syslog-ng.8.xml
  doc/man/syslog-ng.conf.5.xml
  news/bugfix-3349.md
  news/bugfix-3398.md
  news/bugfix-3403.md
  news/bugfix-3405.md
  news/bugfix-3407.md
  news/bugfix-3416.md
  news/bugfix-3426.md
  news/bugfix-3447.md
  news/bugfix-3453.md
  news/bugfix-3466.md
  news/bugfix-3473.md
  news/bugfix-3474.md
  news/developer-note-2526.md
  news/developer-note-3426.md
  news/developer-note-3462.md
  news/feature-3244.md
  news/feature-3358.md
  news/feature-3372.md
  news/feature-3426.md
  news/feature-3437.md
  news/feature-3438.md
  news/feature-3453.md
  news/feature-3474.md
  news/other-3401.md
  packaging/debian/changelog
  packaging/debian/syslog-ng.conf
  packaging/rhel/syslog-ng.conf
  packaging/rhel/syslog-ng.spec
  scl/syslog-ng.conf
Labels: version-bump

#3464 build packages via github actions
  .github/workflows/packages.yml
  dbld/Makefile.am
  dbld/functions.sh
  dbld/rpm
  dbld/rules
  dbld/tarball-changes.ignore
Labels: release-automation

#3502 dbld/rules: remove deb/rpm build from the "release" target
  dbld/rules
Labels: release-automation

#3503 github-actions: build packages nightly
  .github/workflows/packages.yml
Labels: release-automation
