Repository syslog-ng/syslog-ng, pull requests merged in 2020-08, with the labels that each got.

#3373 Stats alias counter
  lib/afinter.c
  lib/stats/stats-registry.c
  lib/stats/stats-registry.h
  lib/stats/tests/CMakeLists.txt
  lib/stats/tests/Makefile.am
  lib/stats/tests/test_alias_ctr_reg.c
Labels: easy

#3369 Use cfg version current
  lib/tests/test_lexer.c
  lib/tests/test_pragma.c
  modules/system-source/system-expand.sh
  tests/functional/globals.py
Labels: easy, enhancement

#3379 Ack tracker refactors
  lib/ack-tracker/CMakeLists.txt
  lib/ack-tracker/Makefile.am
  lib/ack-tracker/ack_tracker.c
  lib/ack-tracker/ack_tracker.h
  lib/ack-tracker/ack_tracker_types.h
  lib/ack-tracker/consecutive_ack_record_container.h
  lib/ack-tracker/consecutive_ack_record_container_dynamic.c
  lib/ack-tracker/consecutive_ack_record_container_static.c
  lib/ack-tracker/consecutive_ack_tracker.c
  lib/ack-tracker/consecutive_ack_tracker.h
  lib/ack-tracker/instant_ack_tracker.c
  lib/ack-tracker/instant_ack_tracker.h
  lib/ack-tracker/late_ack_record_container.h
  lib/ack-tracker/tests/CMakeLists.txt
  lib/ack-tracker/tests/Makefile.am
  lib/ack-tracker/tests/test_consecutive_ack_record_container.c
  lib/ack-tracker/tests/test_late_ack_record_container.c
  lib/afinter.c
  lib/logproto/logproto-buffered-server.c
  lib/logproto/logproto-server.c
  lib/logproto/logproto-server.h
  lib/logreader.c
  lib/logsource.c
  lib/logsource.h
  lib/logthrsource/logthrsourcedrv.c
  lib/logthrsource/logthrsourcedrv.h
  lib/tests/test_logsource.c
  modules/affile/file-reader.c
  modules/affile/regular-files.c
  modules/examples/sources/msg-generator/msg-generator-source.c
  modules/systemd-journal/journal-reader.c
  packaging/debian/copyright
Labels: medium, refactor

#3383 Fixed location reporting and long lines in config errors
  lib/cfg-grammar.y
  lib/cfg-parser.c
  news/bugfix-3383.md
Labels: user-visible-feature

#3381 add dupnames pcre flag
  lib/logmatcher.c
  lib/logmatcher.h
Labels: user-visible-feature

#3387 Threaded ctl command runner
  lib/control/control-server.c
  lib/control/control-server.h
  lib/mainloop.c
  lib/mainloop.h
  lib/stats/stats-control.c
  lib/stats/stats-query-commands.c
  lib/thread-utils.h
  news/bugfix-3349.md
Labels: bug
