Repository syslog-ng/syslog-ng, pull requests merged in 2020-04, with the labels that each got.

#3193 Improve max-connections
  modules/afsocket/afsocket-source.c
  modules/afsocket/afsocket-source.h
  news/other-3193.md
Labels: request-internal-doc, user-visible-feature

#3208 rpm: fix --without maxminddb option
  .github/workflows/macos.yml
  .travis.yml
  news/packaging-3208.md
  packaging/debian/syslog-ng-mod-geoip.install
  packaging/rhel/syslog-ng.spec
Labels: packaging related

#3205 iterate: new template function
  modules/basicfuncs/Makefile.am
  modules/basicfuncs/basic-funcs.c
  modules/basicfuncs/tests/test_basicfuncs.c
  modules/basicfuncs/tf-iterate.c
  news/feature-3205.md
Labels: user-visible-feature
