Repository syslog-ng/syslog-ng, pull requests merged in 2020-07, with the labels that each got.

#3346 panos-parser() source as SCL
  news/feature-3234.md
  scl/CMakeLists.txt
  scl/Makefile.am
  scl/paloalto/panos.conf
  tests/python_functional/functional_tests/parsers/panos/test_panos_parser.py
  tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
Labels: user-visible-feature

#3368 Cfg version current
  lib/cfg.c
  lib/cfg.h
  lib/pragma-grammar.ym
  lib/pragma-parser.c
  news/feature-3368.md
Labels: easy, enhancement

#3229 Limit the size of internal()'s temporary queue
  lib/afinter.c
  lib/afinter.h
  lib/cfg-grammar.y
  lib/versioning.h
  news/other-3229.md
Labels: user-visible-feature

#3361 stats-counter: do not crash when set an external/read-only counter
  lib/stats/stats-counter.h
  lib/stats/tests/test_external_ctr_reg.c
  news/bugfix-3361.md
Labels: bug, easy
